# Generated by Django 4.0.6 on 2022-08-02 08:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.IntegerField(null=True)),
                ('account_type', models.CharField(choices=[('f', 'Fixed'), ('c', 'Current')], max_length=10, null=True)),
                ('balance', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_of_origin', models.CharField(max_length=20, null=True)),
                ('symbol', models.CharField(max_length=5, null=True)),
                ('amount', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25, null=True)),
                ('last_name', models.CharField(max_length=25, null=True)),
                ('address', models.TextField(null=True)),
                ('email', models.EmailField(max_length=50, null=True)),
                ('phone_number', models.CharField(max_length=15, null=True)),
                ('gender', models.CharField(choices=[('f', 'Female'), ('m', 'Male')], max_length=5, null=True)),
                ('age', models.PositiveSmallIntegerField(null=True)),
                ('password', models.IntegerField(null=True)),
                ('country', models.CharField(max_length=15, null=True)),
                ('id_number', models.IntegerField(null=True)),
                ('profile_picture', models.ImageField(null=True, upload_to='profile_picture/')),
                ('date_of_registration', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_type', models.CharField(max_length=30, null=True)),
                ('receipt_date', models.DateField(null=True)),
                ('bill_number', models.IntegerField(null=True)),
                ('receipt_file', models.FileField(upload_to='receipt_file/')),
            ],
        ),
        migrations.CreateModel(
            name='ThirdParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('cost', models.IntegerField(null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thirdparty_account', to='wallet.account')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thirdparty_currency', to='wallet.currency')),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(null=True)),
                ('amount', models.IntegerField(null=True)),
                ('pin', models.TextField(max_length=4, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(max_length=20, null=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_currency', to='wallet.currency')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_customer', to='wallet.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_code', models.CharField(max_length=15, null=True)),
                ('transaction_amount', models.IntegerField(null=True)),
                ('transaction_number', models.IntegerField(null=True)),
                ('transaction_type', models.CharField(choices=[('withd', 'withdraw'), ('depo', 'deposit')], max_length=10, null=True)),
                ('transaction_charge', models.IntegerField(null=True)),
                ('transaction_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('receipt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_receipt', to='wallet.receipt')),
                ('transaction_destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_destination_account', to='wallet.thirdparty')),
                ('transaction_origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_origin_account', to='wallet.account')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_wallet', to='wallet.wallet')),
            ],
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_reward', models.DateTimeField(default=django.utils.timezone.now)),
                ('points', models.IntegerField(null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Reward_customer', to='wallet.customer')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_transaction', to='wallet.transaction')),
            ],
        ),
        migrations.AddField(
            model_name='receipt',
            name='transaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt_transaction', to='wallet.transaction'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=300, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('notification_status', models.CharField(choices=[('r', 'read'), ('un', 'unread')], max_length=7, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_recepient', to='wallet.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_ID', models.IntegerField(null=True)),
                ('amount', models.IntegerField(null=True)),
                ('loan_term', models.IntegerField(null=True)),
                ('interest_rate', models.IntegerField(null=True)),
                ('loan_balance', models.IntegerField(null=True)),
                ('loan_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('due_date', models.IntegerField(null=True)),
                ('guarantor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_guarantor', to='wallet.account')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_wallet', to='wallet.wallet')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardholder_number', models.IntegerField(null=True)),
                ('cardHolder_name', models.CharField(max_length=30, null=True)),
                ('card_type', models.CharField(choices=[('d', 'debit'), ('c', 'credit')], max_length=5, null=True)),
                ('expiry_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('security_code', models.IntegerField(null=True)),
                ('date_issued', models.CharField(max_length=10, null=True)),
                ('issuer', models.CharField(max_length=30, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_account', to='wallet.account')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_wallet', to='wallet.wallet')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_wallet', to='wallet.wallet'),
        ),
    ]
