# Generated by Django 4.0.6 on 2022-09-14 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_remove_customer_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='receipt_file',
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='pin',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
