# Generated by Django 4.0.6 on 2022-10-09 13:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_remove_receipt_receipt_file_alter_customer_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='due_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
