# Generated by Django 4.0.6 on 2022-10-09 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0007_alter_loan_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='due_date',
        ),
    ]
